from pathlib import Path
from ._utils import _read_file


HOME = Path.home() / ".ace"
CONFIG = _read_file(str(HOME / "config.json"))

ASCII_LOGO = r"""
..............................
..AAA.........................
..AA.AA.......................
..AA...AA.....................
..AA.....AA...................
..AA..A....AA.................
..AA..AAA....AA...............
..AA..AA.AA...AA..............
..AA..AA..AAA...AA............
..AA..AA....AAA...AA..........
..AA..AA......AAA...AA........
..AA..AA.......AAA...AA.......
..AA..AA.........AAA...AA.....
..............................
"""


if __name__ == "__main__":
    # print(fuzzy_find(input("Enter query: ")))

    print(HOME)
    pass
